# This is the configuration used to check the rubocop source code.

AllCops:
  Exclude:
    - 'Rakefile'
    - 'bin/**/*'
    - 'Gemfile'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/Documentation:
  Enabled: false

Style/RescueStandardError:
  EnforcedStyle: implicit