name: Ruby Gem

on:
  push:
    branches:
      - master
  pull_request:


jobs:
  build:
    name: Tests and Code Style
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Install sqlite3
        run: sudo apt-get install libsqlite3-dev

      - name: Bundle install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Tests (rspec)
        run: |
          bundle exec rspec
      - name: Code style (Rubocop)
        run: bundle exec rubocop